wi_find_bar/config/routes.rb
Rails.application.routes.draw do
  resources :bars, only: [:index, :show], param: :name, format: false
  root 'bars#index'
end

wi_find_bar/app/models/address.rb
class Address < Characteristic
  acts_as_mappable default_units: :kms,
                   lat_column_name: :lat,
                   lng_column_name: :lng

  # if lat and lng are setted, then there's no need to geocode (isn't too accurate)
  after_create :geocode_address, if: -> { value.present? && lat.blank? && lng.blank? }

  private

  def geocode_address
    geo = Geokit::Geocoders::MultiGeocoder.geocode(value)
    update_attributes(lat: geo.lat, lng: geo.lng)
  end
end

wi_find_bar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

wi_find_bar/app/models/average_price.rb
class AveragePrice < Characteristic
end

wi_find_bar/app/models/bar.rb
class Bar < ApplicationRecord
  has_many :characteristics

  validates :name, presence: true

  def address
    Address.find_by(bar_id: id)
  end

  def has_wifi
    HasWifi.find_by(bar_id: id)
  end
end

wi_find_bar/app/models/bar_agency.rb
class BarAgency
  def search_all_bars
    Bar.all
  end

  def search_and_filter(filters)
    bars = Bar.all.to_a
    filters.each do |filter|
      bars = bars.select { |bar| filter.check(bar) }
    end
    Bar.where(id: bars.map(&:id))
  end
end

wi_find_bar/app/models/bar_registry.rb
class BarRegistry
  def all_approved_bars
    Bar.all
  end

  def bar_by_name(bar_name)
    Bar.find_by(name: bar_name)
  end
end

wi_find_bar/app/models/capacity.rb
class Capacity < Characteristic
end

wi_find_bar/app/models/cartographer.rb
class Cartographer
  def distance_between(from, to)
    to.distance_to(from, units: :kms)
  end

  def show_map(address)
    "http://maps.google.com/maps/api/staticmap?size=2000x2000&markers=color:blue|label:A|
    #{address}&key=AIzaSyD3KTrkOMrIxA95d-QOnfyaofqRRpoAEd8"
  end
end

wi_find_bar/app/models/characteristic.rb
class Characteristic < ApplicationRecord
  belongs_to :bar

  validates :value, presence: true

  def value
    self[:value]
  end
end

wi_find_bar/app/models/close_time.rb
class CloseTime < Characteristic
end

wi_find_bar/app/models/email.rb
class Email < Characteristic
end

wi_find_bar/app/models/filter.rb
class Filter
  attr_accessor :validators

  def initialize(validators)
    @validators = validators
  end

  def check(bar)
    validators.each do |v|
      return false unless v.check(bar)
    end
    true
  end
end

wi_find_bar/app/models/filter_by_distance.rb
class FilterByDistance < Filter
  attr_accessor :address, :distance

  def initialize(address, distance)
    @address = address
    @distance = distance
  end

  def check(bar)
    Cartographer.new.distance_from_to(address, bar.address) <= distance
  end
end

wi_find_bar/app/models/has_wifi.rb
class HasWifi < Characteristic
end

wi_find_bar/app/models/location.rb
class Location < ApplicationRecord
  belongs_to :bar

  acts_as_mappable default_units: :kms,
                   lat_column_name: :lat,
                   lng_column_name: :lng

  # if lat and lng are setted, then there's no need to geocode (isn't too accurate)
  after_create :geocode_address, if: -> { address.present? && lat.blank? && lng.blank? }

  private

  def geocode_address
    geo = Geokit::Geocoders::MultiGeocoder.geocode(address)
    update_attributes(lat: geo.lat, lng: geo.lng)
  end
end

wi_find_bar/app/models/opening_time.rb
class OpeningTime < Characteristic
end

wi_find_bar/app/models/phone_number.rb
class PhoneNumber < Characteristic
end

wi_find_bar/app/models/plug_quantity.rb
class PlugQuantity < Characteristic
end

wi_find_bar/app/models/public_bar_agency.rb
class PublicBarAgency
  def search_all_bars
    BarRegistry.new.all_approved_bars
  end

  def search_and_filter(filter)
    bars = search_all_bars.to_a
    bars = bars.select { |bar| filter.check(bar) }
    Bar.where(id: bars.map(&:id))
  end

  def search_bar_by_name(bar_name)
    BarRegistry.new.bar_by_name(bar_name)
  end
end

wi_find_bar/app/models/validator.rb
class Validator
  def check(_bar)
    raise NotImplementedError, 'Implement this method in a child class'
  end
end

wi_find_bar/app/models/web_page.rb
class WebPage < Characteristic
end

wi_find_bar/app/controllers/bars_controller.rb
class BarsController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  def index
    bars_scope = filter if should_filter?
    bars_scope ||= PublicBarAgency.new.search_all_bars
    @bars = smart_listing_create :bars, bars_scope, partial: 'bars/list',
                                                    default_sort: { name: 'asc' }
  end

  def show
    @bar = PublicBarAgency.new.search_bar_by_name(params[:name])
  end

  private

  def should_filter?
    include_filter?(filter_has) || include_filter?(filter_greater) ||
      include_filter?(filter_less) || params_for_distance_range?
  end

  def include_filter?(filter_name)
    filter_name.present? && any_valid?(filter_name)
  end

  def filter
    PublicBarAgency.new.search_and_filter(Filter.new(validators))
  end

  def filter_has
    @filter_has ||= params[:filter_has]
  end

  def filter_greater
    @filter_greater ||= params[:filter_greater]
  end

  def filter_less
    @filter_less ||= params[:filter_less]
  end

  def filter_distance
    @filter_distance ||= params[:filter_distance]
  end

  def params_for_distance_range?
    return false unless filter_distance.present?
    filter_distance[:address].present? && filter_distance[:distance].present?
  end

  def any_valid?(filter_option)
    filter_option.each do |_key, value|
      return true if value.present?
    end
    false
  end

  def validators
    res = []
    validator_by_characteristics(res, filter_has, BarHasCharacteristic) if
      filter_has.present?
    validator_by_characteristics(res, filter_greater, BarCharacteristicsGreater) if
      filter_greater.present?
    validator_by_characteristics(res, filter_less, BarCharacteristicsLess) if
      filter_less.present?
    validator_by_distance(res) if params_for_distance_range?
    res
  end

  def validator_by_characteristics(res, filter_option, klass)
    filter_option.each do |key, value|
      res << klass.new(key.classify.constantize.new(value: value)) if
        value.present?
    end
  end

  def validator_by_distance(res)
    res << ValidatorByDistance.new(filter_distance[:address], filter_distance[:distance].to_f)
  end
end

wi_find_bar/app/views/bars/_bar_row.html.slim
.title-bar
  = link_to bar.name, bar_path(bar, name: bar.name)
.data-bar
  .item-data-bar
    .item-data-bar-name
      | Ubicación
    .item-data-bar-data
      = bar.address.value
  .item-data-bar
    .item-data-bar-name
      | Latitud
    .item-data-bar-data
      = bar.address.lat
  .item-data-bar
    .item-data-bar-name
      | Longitud
    .item-data-bar-data
      = bar.address.lng
  .item-data-bar
    .item-data-bar-name
      | Tiene Wifi
    .item-data-bar-data
      = t("#{bar.has_wifi.value}Value")
.data-bar
  - bar.characteristics.each do |c|
    - unless c.type == 'Address' || c.type == 'HasWifi'
      .item-data-bar
        .item-data-bar-name
          = t("#{c.type}")
        .item-data-bar-data
          = c.value

wi_find_bar/app/views/bars/_list.html.slim
.list-bars
  .title
    | Bares
  .list
    - smart_listing.collection.each do |b|
      .item-bar
        = render 'bar_row', bar: b

wi_find_bar/app/views/bars/index.html.slim
.bars-index
  .filter-options
    = smart_listing_controls_for(:bars, {class: "form-inline text-right"}) do
      .filter-title
        | Wifi:
      .option
        = radio_button_tag 'filter_has[has_wifi]', '', true, class: 'radio-button-option'
        = label_tag :wifi, 'Indistinto', class: 'option-text'
      .option
        = radio_button_tag 'filter_has[has_wifi]', 'true', false, class: 'radio-button-option'
        = label_tag :wifi, 'Tiene WiFi', class: 'option-text'
      .option
        = radio_button_tag 'filter_has[has_wifi]', 'false', false, class: 'radio-button-option'
        = label_tag :wifi, 'No tiene WiFi', class: 'option-text'
      .filter-title
        | Distancia (en Kms):
      .option
        = text_field_tag 'filter_distance[address]', '', class: "placeholder-direction",
                                        placeholder: "Dirección", autocomplete: :off
        = number_field_tag 'filter_distance[distance]', '', class: 'distance-input', min: 0, value: 0.4, step: 0.1      
      .filter-title
        | Email:
      .option
        = text_field_tag 'filter_has[email]', '', class: "placeholder-direction",
                                        placeholder: "example@domain.com", autocomplete: :off
      .filter-title
        | Horario de Apertura:
      .option
        = text_field_tag 'filter_has[opening_time]', '', class: "placeholder-direction",
                                        placeholder: "10.00", autocomplete: :off
      .filter-title
        | Horario de Cierre:
      .option
        = text_field_tag 'filter_has[close_time]', '', class: "placeholder-direction",
                                        placeholder: "19.00", autocomplete: :off
      .filter-title
        | Número de Teléfono:
      .option
        = text_field_tag 'filter_has[phone_number]', '', class: "placeholder-direction",
                                        placeholder: "(186)285-7925", autocomplete: :off
      .filter-title
        | Página Web:
      .option
        = text_field_tag 'filter_has[web_page]', '', class: "placeholder-direction",
                                        placeholder: "http://example.com/clotilde.swift", autocomplete: :off
      .filter-title
        | Capacidad:
      .option-min-max
        .option-min
          | Mínimo:
          = number_field_tag 'filter_greater[capacity]', '', class: 'min-max-input', min: 0
        .option-max
          | Máximo:
          = number_field_tag 'filter_less[capacity]', '', class: 'min-max-input', min: 0
      .filter-title
        | Precio Promedio:
      .option-min-max
        .option-min
          | Mínimo:
          = number_field_tag 'filter_greater[average_price]', '', class: 'min-max-input', min: 0, step: 0.1
        .option-max
          | Máximo:
          = number_field_tag 'filter_less[average_price]', '', class: 'min-max-input', min: 0, step: 0.1
      .filter-title
        | Cantidad de Enchufes:
      .option-min-max
        .option-min
          | Mínimo:
          = number_field_tag 'filter_greater[plug_quantity]', '', class: 'min-max-input', min: 0
        .option-max
          | Máximo:
          = number_field_tag 'filter_less[plug_quantity]', '', class: 'min-max-input', min: 0
  .bars-index-list
    = smart_listing_render :bars

wi_find_bar/app/views/bars/index.js.erb
<%= smart_listing_update(:bars) %>

wi_find_bar/app/views/bars/show.html.slim
.show-bar
  .side-bar
    .bar-title
      = @bar.name
    .bar-body
      .location
        .address
          = @bar.address.value
        .item
          .item-name
            | Latitud:
          .item-data
            = @bar.address.lat
        .item
          .item-name
            | Longitud:
          .item-data
            = @bar.address.lng
      .information
        - @bar.characteristics.each do |c|
          - unless c.type == 'Address'
            .item-data-bar-name
              = t("#{c.type}")
            .item-data-bar-data
              - if c.type == 'HasWifi'
                = t("#{c.value}Value")
              - else
                = c.value
  .map-bar
    = image_tag Cartographer.new.show_map(@bar.address.value)
= link_to "Back", :back